# Generated by Django 3.0.1 on 2019-12-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='resumen',
            field=models.TextField(blank=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
    ]
