# Generated by Django 3.0.1 on 2019-12-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20191230_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Libros',
        ),
    ]
